server:
  port: 4000

spring:
  application:
    name: petHotel
  datasource:
    url: jdbc:mysql://localhost:3306/pet-hotel?serverTimezone=Asia/Seoul
    username: root
    password: ROQKFdlehdaud12!@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  jwt:
    secretKey: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


